# Generated by Django 4.1.2 on 2022-11-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_professor',
            field=models.BooleanField(default=False),
        ),
    ]
