# Generated by Django 4.1 on 2022-10-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dontpadcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dontpadurl',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
