# Generated by Django 4.1.2 on 2022-11-07 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dontpadcode', '0002_alter_dontpadurl_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DontpadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dontpadcode.dontpadurl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
