# Generated by Django 4.1.2 on 2022-11-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dontpadcode', '0005_dontpadcomment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DontpadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
