# Generated by Django 4.1.2 on 2022-11-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dontpadcode', '0006_dontpadimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DontpadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dontpadcode.dontpadurl')),
            ],
        ),
    ]
