# Generated by Django 4.1.2 on 2022-11-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dontpadcode', '0007_dontpadvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dontpadvideo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
