# Generated by Django 4.1.2 on 2022-11-27 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dontpadcode', '0008_dontpadvideo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DontpadUserCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('proffesor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proffesor_code', to='dontpadcode.dontpadcode')),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_url', to='dontpadcode.dontpadurl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
