# Generated by Django 4.1.2 on 2022-12-03 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dontpadcode', '0009_dontpadusercode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DontpadExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('codeInput', models.TextField()),
                ('hints', models.TextField(blank=True, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dontpadcode.dontpadcode')),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dontpadcode.dontpadurl')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='dontpadusercode',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='DontpadExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('result', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('solved', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='dontpadcode.dontpadexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
