# Generated by Django 4.1.2 on 2022-12-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dontpadcode', '0011_remove_dontpadexercise_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dontpadexercise',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='dontpadexercise',
            name='exerciseSlug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dontpadexercise',
            name='title',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
