# Generated by Django 4.1.2 on 2022-12-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dontpadcode', '0012_alter_dontpadexercise_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dontpadexerciseresult',
            name='code',
        ),
    ]
