# Generated by Django 4.1.2 on 2022-12-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dontpadcode', '0013_remove_dontpadexerciseresult_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DontpadVideoAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dontpadcode.dontpadurl')),
            ],
        ),
        migrations.CreateModel(
            name='DontpadVideoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dontpadcode.dontpadvideoaudio')),
            ],
        ),
    ]
