# Generated by Django 4.1.2 on 2022-12-13 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dontpadcode', '0014_dontpadvideoaudio_dontpadvideocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='dontpadvideocode',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dontpadvideocode',
            name='url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dontpadcode.dontpadurl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dontpadvideocode',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dontpadcode.dontpadcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dontpadvideocode',
            name='audio',
            field=models.FileField(upload_to='audio/'),
        ),
        migrations.DeleteModel(
            name='DontpadVideoAudio',
        ),
    ]
