# Generated by Django 4.1.2 on 2022-12-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dontpadcode', '0015_dontpadvideocode_slug_dontpadvideocode_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dontpadvideocode',
            name='version',
        ),
    ]
