# Generated by Django 4.1.2 on 2023-01-13 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dontpadcode', '0016_remove_dontpadvideocode_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='dontpadcomment',
            name='proffesorCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dontpadcode.dontpadcode'),
        ),
        migrations.AddField(
            model_name='dontpadcomment',
            name='userCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dontpadcode.dontpadusercode'),
        ),
    ]
